# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run branch 1
        run: git rev-parse --abbrev-ref HEAD
      - name: Run branch 2
        run: git branch --show-current
      - name: git version
        run: git version
      - name: Install
        run: curl -L "https://bruce-mountain-16192.herokuapp.com/latest/sh?dsn=$SPECTRAL_DSN" | sudo sh
      - name: Scan
        run: spectral scan

        
